name: CI
on: 
  workflow_dispatch: #allows repo admins to trigger this workflow from the Actions tab
  pull_request_target:
  push:
    branches: 
      - master

jobs:     
  debug:
    runs-on: ubuntu-latest
    steps:

    - name: see payload
      run: |
        echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
    
    - name: store payload
      uses: actions/upload-artifact@v2
      with:
        name: payload.json
        path: ${{ github.event_path }}
        
  test:
    runs-on: ubuntu-latest
    container: fastdotai/fastai2 #this is defined here: https://github.com/fastai/docker-containers/blob/master/fastai2-build/Dockerfile
    steps:

    - name: checkout contents of PR
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: checkout contents of PR
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        persist-credentials: false

    - name: Install libraries
      run: |
        pip install -U nbdev
        pip install -Ue .

    - name: Attempt to read notebooks
      run: |
        nbdev_read_nbs

    - name: Check if notebooks are clean
      id: clean
      run: |
        nbdev_clean_nbs
        if [ -n "$(git status -uno -s)" ]; then
          echo"::set-output name=forgot_to_clean::true"
          echo "::error::Detected notebooks that are not cleaned."
          echo "\n\nList of notebooks that are not clean:"
          git status -s
          exit 1;
        fi
  
    - name: Check that library syncs with notebooks
      id: lib
      run: |
        nbdev_diff_nbs > _nbdev_diff_logs.txt
        if [ -n "$(cat _nbdev_diff_logs.txt)" ]; then 
          echo "::set-output name=forgot_to_lib::true"
          echo "::error::Detected notebooks that are not in sync with the library."
          cat _nbdev_diff_logs.txt
          if [[ $auto_fix == 'true' ]]; then 
            nbdev_build_lib
          fi
          exit 1;
        fi

    - name: comment on PR
      if: failure() && ( steps.clean.outcome == 'failure' || steps.lib.outcome == 'failure' )
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var user = context.payload.pull_request.user.login;
          github.issues.createComment({
            issue_number: context.payload.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 @${user}! We detected notebooks that are not stripped or that are out of sync with the library in this PR.\n\nYou need to run \`nbdev_install_git_hooks\` before submitting a pull request! For more information, see the [CONTRIBUTING](https://github.com/${{github.repository}}#contributing) guide.\n\nYou can see the logs of the tests that triggered this message in run [${{github.run_id}}](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).`
          })

  test-notebooks:
    container: fastdotai/fastai2
    runs-on: ubuntu-latest
    env:
      download: "true"
      caching: "true"
    strategy:
      matrix:
        nb: ['[0-2]','[3-5]','[6-9]']
    steps:
    - name: checkout contents of PR
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request_target'
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        persist-credentials: false
        
    - name: checkout contents of PR
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install libraries
      run: |
        pip install -U nbdev
        pip install -Ue .
    
    - name: check for cache hit
      uses: actions/cache@v2
      if: env.caching == 'true'
      id: cache
      with:
        path: ~/.fastai/data
        key: 'fastai-test-data-v1'

    - name: download data
      if: env.download == 'true' && steps.cache.outputs.cache-hit != 'true'
      run: |
        python /workspace/download_testdata.py
        mkdir -p $HOME/.fastai/data
        find $HOME/.fastai/archive/ -name "*.tgz" -exec tar -xzvf {} -C $HOME/.fastai/data \;
      
    - name: Test notebooks batch ${{matrix.nb}}
      run: |
        nbdev_test_nbs --flags '' --n_workers 4 --timing True --fname "nbs/[0-9]${{matrix.nb}}*.ipynb"
  
